<?php
/**
 * Created by PhpStorm.
 * User: crime
 * Date: 2018-04-18
 * Time: 09:51
 */

namespace Controllers;

use Core\security;
use Services\globals;
use Services\links;

class user_controller extends controller
{
//    public function __construct()
//    {
//        $this->directory = globals::get('VIEWS').'/user';
//    }

    function view($view)
    {
        security::access();
        parent::view($view); // TODO: Change the autogenerated stub
    }


    function home()
    {
        return links::get('dashboard');
    }
}